version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: logistics-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: logistics
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3-management
    container_name: logistics-rabbit
    ports:
      - "5672:5672"   # messaging
      - "15672:15672" # mgmt UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
  keycloak-db:
    image: postgres:15
    container_name: keycloak-db
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - keycloak_data:/var/lib/postgresql/data
    ports:
      - "5433:5432" # optional for access

#  keycloak:
#    image: quay.io/keycloak/keycloak:24.0.3
#    container_name: logistics-keycloak
#    command: start-dev --import-realm
#    environment:
#      KEYCLOAK_ADMIN: admin
#      KEYCLOAK_ADMIN_PASSWORD: admin
#      KC_DB: dev-mem
#    ports:
#      - "8082:8080"
#    volumes:
#      - ./keycloak:/opt/keycloak/data/import

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.3
    container_name: logistics-keycloak
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: sahithi1234
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
    ports:
      - "8082:8080"
    depends_on:
      - keycloak-db

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smart-logistics-tracker
    depends_on:
      - mysql
      - rabbitmq
      - keycloak
    ports:
      - "2045:2045"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/logistics?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://keycloak:8082/realms/smart-logistics-tracker

volumes:
  mysql_data:
  keycloak_data:
